app:
  host: "0.0.0.0"
  port: 9009
  log_level: "debug"

database:
  host: "127.0.0.1"
  port: 5432
  username: "root"
  password: "test"
  name: "test"
  max_idle_connections: 2
  max_active_connections: 10
  max_connection_lifetime: 2

minio:
  base_url: "localhost:9001"
  serve_url: "http://localhost:9001"
  key: "MINIO_ACCESS_KEY"
  secret: "MINIO_SECRET_KEY"
  bucket: "shopicano"
  location: "us"
  sign_duration: 5

payment_gateway:
  name: "stripe"
  configs:
    secret_key: "{STRIPE_SECRET_KEY}"
    success_callback: "{IPN_SUCCESS_CALLBACK}"
    failure_callback: "{IPN_FAILURE_CALLBACK}"
